language: clojure
lein: lein
before_script: sqlite3 -version
script: lein test-all
jdk:
  - openjdk8
  - openjdk11
  - oraclejdk11
branches:
  only:
    - master
    - paren-joins
after_success:
    - CLOVERAGE_VERSION=1.1.2 lein cloverage --codecov --runner :midje
    - bash <(curl -s https://codecov.io/bash)
